name: Build timeszones

on:
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '42 0 * * *'
permissions:
  contents: write
  
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: jiro4989/setup-nim-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate timezones
        run: |
          cd tools
          nimble install chrono
          nim c generate.nim
          ./generate

          if [ `stat -c %s tzdata.json` -lt 1000000 ]; then
            echo "tzdata.json is less than 1mb. This is unexpecetd as it's normally around one floppy disk in length. Please check."
            exit 1
          fi
  
      - name: Commit if changed
        run: |
          rm init.sh
          git checkout main
          mv tools/tzdata.json dist/tzdata.json
          mv tools/tzdata/dstchanges.csv dist/dstchanges.csv
          mv tools/tzdata/timezones.csv dist/timezones.csv
          if [[ `git status --porcelain` ]]; then
            echo "Changes detected in the repository."
            git status
            echo "TODO"
            exit 1
          else
            echo "No changes detected in the repository."
          fi
