name: Build timeszones

on:
  pull_request:
    branches:
      - '**'
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: jiro4989/setup-nim-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate timezones
        run: |
          cd tools
          nimble install chrono
          nim c generate.nim
          ./generate

          if [ `stat -c %s tzdata.json` -lt 1000000 ]; then
            echo "tzdata.json is less than 1mb. This is unexpecetd as it's normally around one floppy disk in length. Please check."
            exit 1
          fi
  
      - name: Commit if changed
        run: |
          mv ./tzdata.json ../dist/tzdata-all.json
          cd ..
          if [[ `git status --porcelain` ]]; then
            echo "Changes detected in the repository. Committing."
            git status
            git add dist/tzdata-all.json
            git config --local user.email "tz@frameos.net"
            git config --local user.name "Timezone Bot"
            git commit -m "Update tzdata-all.json"
            git push
            echo "Changes committed."
          else
            echo "No changes detected in the repository."
          fi
