name: Build timeszones

on:
  pull_request:
    branches:
      - '**'
  # schedule:
  #   - cron: '0 0 * * *'

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: jiro4989/setup-nim-action@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate timezones
        run: |
          cd tools
          nim c generate.nim
          ./generate
  
      - name: Check for snapshot modifications
        run: |
          rm init.sh
          if [[ `git status --porcelain` ]]; then
            echo "Changes detected in the repository after running visual regression tests."
            echo "Run the following locally to fix:"
            echo "- cd tools"
            echo "- num r generate.nim"
            git status
            git diff
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "No changes detected in the repository."
            echo "changes_detected=false" >> $GITHUB_ENV
          fi

      - name: Fail if changes detected
        if: env.changes_detected == 'true'
        run: exit 1
